import { defaultSettings } from "./calculator";
import type { Workspace } from "./types";
export const demo: Workspace = {
  settings: defaultSettings,
  projects: [
    {
      id: "1",
      name: "Vaso paramétrico",
      description: "Uma nova forma de deixar a casa mais verde.",
      emoji: "🌿",
      material: "PLA",
      status: "Em impressão",
      grams: 180,
      hours: 6.5,
      createdAt: "2026-09-16",
    },
    {
      id: "2",
      name: "Luminária orbital",
      description: "Luz, camadas e um pouco de personalidade.",
      emoji: "💡",
      material: "PETG",
      status: "Planejado",
      grams: 320,
      hours: 12,
      createdAt: "2026-09-15",
    },
    {
      id: "3",
      name: "Organizador de mesa",
      description: "Cada coisa no seu lugar. Com o seu estilo.",
      emoji: "✏️",
      material: "PLA",
      status: "Concluído",
      grams: 125,
      hours: 4,
      createdAt: "2026-09-14",
    },
    {
      id: "4",
      name: "Mini astronauta",
      description: "Um pequeno explorador para a sua coleção.",
      emoji: "🧑‍🚀",
      material: "PLA",
      status: "Concluído",
      grams: 85,
      hours: 3.5,
      createdAt: "2026-09-13",
    },
  ],
  transactions: [
    {
      id: "1",
      description: "Filamento PLA · Ciano 1 kg",
      type: "Compra",
      category: "Filamento",
      amount: 95,
      date: "2026-09-16",
      projectId: "",
    },
    {
      id: "2",
      description: "Organizador de mesa · 3 unidades",
      type: "Venda",
      category: "Peça impressa",
      amount: 210,
      date: "2026-09-15",
      projectId: "3",
    },
    {
      id: "3",
      description: "Mini astronauta · Encomenda",
      type: "Venda",
      category: "Peça impressa",
      amount: 85,
      date: "2026-09-14",
      projectId: "4",
    },
    {
      id: "4",
      description: "Filamento PETG · Natural 1 kg",
      type: "Compra",
      category: "Filamento",
      amount: 110,
      date: "2026-09-12",
      projectId: "",
    },
  ],
};
