export type Project = {
  allocationMode?: "project";
  soldQuantity?: number;
  personalQuantity?: number;
  giftQuantity?: number;
  saleStatus?: "unsold" | "partial" | "sold";
  soldAt?: string;
  soldRevenue?: number;
  soldCost?: number;
  personalCost?: number;
  materialCost?: number;
  energyCost?: number;
  personalAt?: string;
  hasImage?: boolean;
  quoteCount?: number;
  projectCount?: number;
  componentIds?: string[];
  total?: number;
  cost?: number;
  id: string;
  name: string;
  description: string;
  emoji: string;
  material: string;
  status: "Planejado" | "Em impressão" | "Concluído";
  grams: number;
  hours: number;
  createdAt: string;
};
export type Transaction = {
  sourceFilamentId?: string;
  productionCost?: number;
  materialCost?: number;
  kind?: "investment" | "project-sale" | "manual";
  sourceProjectId?: string;
  sourceQuoteId?: string;
  id: string;
  description: string;
  type: "Compra" | "Venda";
  category: string;
  amount: number;
  date: string;
  projectId: string;
};
export type Settings = {
  filamentPrice: number;
  spoolWeight: number;
  power: number;
  energyRate: number;
  machineRate: number;
  laborRate: number;
  failureRate: number;
  margin: number;
};
export type Workspace = {
  filaments?: Filament[];
  projects: Project[];
  transactions: Transaction[];
  settings: Settings;
};
export type Filament = {
  id: string;
  name: string;
  brand: string;
  material: "PLA" | "PETG" | "ABS" | "ASA" | "TPU" | "Outro";
  color: string;
  colorName: string;
  price: number;
  weight: number;
  depleted: boolean;
  createdAt: string;
};
